/*
                Copyright (C) 2005, ..., 2010 Joseph L. Chuma

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
//---------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "SplashScreen.h"
//---------------------------------------------------------------------
USERES("extrema.res");
USEFORM("Forms\extremaMain.cpp", MainForm);
USEFORM("Forms\ArrowChooser.cpp", ArrowChooserForm);
USEFORM("Forms\DigitizeInfo.cpp", DigitizeInfoForm);
USEFORM("Forms\DigitizePNG.cpp", DigitizePNGForm);
USEFORM("Forms\Display.cpp", DisplayForm);
USEFORM("Forms\ExecuteForm.cpp", ExecForm);
USEFORM("Forms\FigureDraw.cpp", FigureDrawForm);
USEFORM("Forms\FitForm.cpp", FitCommandForm);
USEFORM("Forms\GenerateCommandForm.cpp", GenerateCmndForm);
USEFORM("Forms\GetCoordinates.cpp", GetCoordinatesForm);
USEFORM("Forms\GraphForm.cpp", GraphCommandForm);
USEFORM("Forms\GraphicsSubwindow.cpp", GraphicsSubwindowForm);
USEFORM("Forms\HistogramType.cpp", HistogramTypeForm);
USEFORM("Forms\Inquire.cpp", InquireForm);
USEFORM("Forms\InquireYN.cpp", InquireYNForm);
USEFORM("Forms\MainGraphicsWindow.cpp", MainGraphicsForm);
USEFORM("Forms\PeakFinding.cpp", PeakFindingForm);
USEFORM("Forms\PNGDisplay.cpp", PNGForm);
USEFORM("Forms\ProgressDisplay.cpp", ProgressForm);
USEFORM("Forms\ReadMatrixForm.cpp", ReadMatForm);
USEFORM("Forms\ReadScalarsForm.cpp", ReadScalForm);
USEFORM("Forms\ReadTextForm.cpp", ReadTxtForm);
USEFORM("Forms\ReadVectorsForm.cpp", ReadVecForm);
USEFORM("Forms\SelectColor.cpp", SelectColorForm);
USEFORM("Forms\SelectFont.cpp", SelectFontForm);
USEFORM("Forms\SelectLineWidth.cpp", SelectLineWidthForm);
USEFORM("Forms\SplashScreen.cpp", SplashScreenForm);
USEFORM("Forms\TextInteractive.cpp", TextCommandForm);
USEFORM("Forms\VarInfo.cpp", VarInfoForm);
USEFORM("Forms\VarShow.cpp", VarShowForm);
USEFORM("Forms\WriteMatrixForm.cpp", WriteMatForm);
USEFORM("Forms\WriteScalarsForm.cpp", WriteScalForm);
USEFORM("Forms\WriteTextForm.cpp", WriteTxtForm);
USEFORM("Forms\WriteVectorsForm.cpp", WriteVecForm);
USEUNIT("Commands\CMD_bin2d.cpp");
USEUNIT("Commands\CMD_bin.cpp");
USEUNIT("Commands\CMD_clear.cpp");
USEUNIT("Commands\CMD_contour.cpp");
USEUNIT("Commands\CMD_defaults.cpp");
USEUNIT("Commands\CMD_define.cpp");
USEUNIT("Commands\CMD_destroy.cpp");
USEUNIT("Commands\CMD_display.cpp");
USEUNIT("Commands\CMD_do.cpp");
USEUNIT("Commands\CMD_enddo.cpp");
USEUNIT("Commands\CMD_endif.cpp");
USEUNIT("Commands\CMD_evaluateExpression.cpp");
USEUNIT("Commands\CMD_execute.cpp");
USEUNIT("Commands\CMD_figure.cpp");
USEUNIT("Commands\CMD_filter.cpp");
USEUNIT("Commands\CMD_fit.cpp");
USEUNIT("Commands\CMD_generate.cpp");
USEUNIT("Commands\CMD_get.cpp");
USEUNIT("Commands\CMD_goto.cpp");
USEUNIT("Commands\CMD_graph.cpp");
USEUNIT("Commands\CMD_grid.cpp");
USEUNIT("Commands\CMD_hardcopy.cpp");
USEUNIT("Commands\CMD_help.cpp");
USEUNIT("Commands\CMD_if.cpp");
USEUNIT("Commands\CMD_inquire.cpp");
USEUNIT("Commands\CMD_list.cpp");
USEUNIT("Commands\CMD_matrix.cpp");
USEUNIT("Commands\CMD_pause.cpp");
USEUNIT("Commands\CMD_quit.cpp");
USEUNIT("Commands\CMD_read.cpp");
USEUNIT("Commands\CMD_rebin.cpp");
USEUNIT("Commands\CMD_replot.cpp");
USEUNIT("Commands\CMD_return.cpp");
USEUNIT("Commands\CMD_save.cpp");
USEUNIT("Commands\CMD_scalar.cpp");
USEUNIT("Commands\CMD_scales.cpp");
USEUNIT("Commands\CMD_set.cpp");
USEUNIT("Commands\CMD_show.cpp");
USEUNIT("Commands\CMD_sort.cpp");
USEUNIT("Commands\CMD_statistics.cpp");
USEUNIT("Commands\CMD_text.cpp");
USEUNIT("Commands\CMD_vector.cpp");
USEUNIT("Commands\CMD_window.cpp");
USEUNIT("Commands\CMD_world.cpp");
USEUNIT("Commands\CMD_write.cpp");
USEUNIT("Commands\CMD_zerolines.cpp");
USEUNIT("Commands\Command.cpp");
USEUNIT("Commands\CommandTable.cpp");
USEUNIT("Functions\FCN_abs.cpp");
USEUNIT("Functions\FCN_acos.cpp");
USEUNIT("Functions\FCN_acosd.cpp");
USEUNIT("Functions\FCN_acot.cpp");
USEUNIT("Functions\FCN_acotd.cpp");
USEUNIT("Functions\FCN_acsc.cpp");
USEUNIT("Functions\FCN_acscd.cpp");
USEUNIT("Functions\FCN_aerf.cpp");
USEUNIT("Functions\FCN_aerfc.cpp");
USEUNIT("Functions\FCN_agauss.cpp");
USEUNIT("Functions\FCN_airy.cpp");
USEUNIT("Functions\FCN_asec.cpp");
USEUNIT("Functions\FCN_asecd.cpp");
USEUNIT("Functions\FCN_asin.cpp");
USEUNIT("Functions\FCN_asind.cpp");
USEUNIT("Functions\FCN_atan2.cpp");
USEUNIT("Functions\FCN_atan2d.cpp");
USEUNIT("Functions\FCN_atan.cpp");
USEUNIT("Functions\FCN_atand.cpp");
USEUNIT("Functions\FCN_bei.cpp");
USEUNIT("Functions\FCN_ber.cpp");
USEUNIT("Functions\FCN_besi0.cpp");
USEUNIT("Functions\FCN_besi1.cpp");
USEUNIT("Functions\FCN_besj0.cpp");
USEUNIT("Functions\FCN_besj1.cpp");
USEUNIT("Functions\FCN_besk0.cpp");
USEUNIT("Functions\FCN_besk1.cpp");
USEUNIT("Functions\FCN_besy0.cpp");
USEUNIT("Functions\FCN_besy1.cpp");
USEUNIT("Functions\FCN_beta.cpp");
USEUNIT("Functions\FCN_betain.cpp");
USEUNIT("Functions\FCN_binom.cpp");
USEUNIT("Functions\FCN_biry.cpp");
USEUNIT("Functions\FCN_bivarnor.cpp");
USEUNIT("Functions\FCN_cheby.cpp");
USEUNIT("Functions\FCN_chisq.cpp");
USEUNIT("Functions\FCN_chisqi.cpp");
USEUNIT("Functions\FCN_chlogu.cpp");
USEUNIT("Functions\FCN_clebsg.cpp");
USEUNIT("Functions\FCN_cos.cpp");
USEUNIT("Functions\FCN_cosd.cpp");
USEUNIT("Functions\FCN_cosint.cpp");
USEUNIT("Functions\FCN_cot.cpp");
USEUNIT("Functions\FCN_cotd.cpp");
USEUNIT("Functions\FCN_csc.cpp");
USEUNIT("Functions\FCN_cscd.cpp");
USEUNIT("Functions\FCN_date.cpp");
USEUNIT("Functions\FCN_dawson.cpp");
USEUNIT("Functions\FCN_digamma.cpp");
USEUNIT("Functions\FCN_dilog.cpp");
USEUNIT("Functions\FCN_ei.cpp");
USEUNIT("Functions\FCN_einellic.cpp");
USEUNIT("Functions\FCN_ellice.cpp");
USEUNIT("Functions\FCN_ellick.cpp");
USEUNIT("Functions\FCN_eltime.cpp");
USEUNIT("Functions\FCN_erf.cpp");
USEUNIT("Functions\FCN_erfc.cpp");
USEUNIT("Functions\FCN_exp.cpp");
USEUNIT("Functions\FCN_expand.cpp");
USEUNIT("Functions\FCN_expint.cpp");
USEUNIT("Functions\FCN_expn.cpp");
USEUNIT("Functions\FCN_factorial.cpp");
USEUNIT("Functions\FCN_ferdirac.cpp");
USEUNIT("Functions\FCN_finellic.cpp");
USEUNIT("Functions\FCN_fisher.cpp");
USEUNIT("Functions\FCN_frec1.cpp");
USEUNIT("Functions\FCN_frec2.cpp");
USEUNIT("Functions\FCN_fres1.cpp");
USEUNIT("Functions\FCN_fres2.cpp");
USEUNIT("Functions\FCN_gamma.cpp");
USEUNIT("Functions\FCN_gammacin.cpp");
USEUNIT("Functions\FCN_gammain.cpp");
USEUNIT("Functions\FCN_gammatin.cpp");
USEUNIT("Functions\FCN_gammln.cpp");
USEUNIT("Functions\FCN_gammq.cpp");
USEUNIT("Functions\FCN_gauss.cpp");
USEUNIT("Functions\FCN_gaussin.cpp");
USEUNIT("Functions\FCN_hermite.cpp");
USEUNIT("Functions\FCN_hypgeo.cpp");
USEUNIT("Functions\FCN_int.cpp");
USEUNIT("Functions\FCN_jacobi.cpp");
USEUNIT("Functions\FCN_jahnuf.cpp");
USEUNIT("Functions\FCN_kei.cpp");
USEUNIT("Functions\FCN_ker.cpp");
USEUNIT("Functions\FCN_laguerre.cpp");
USEUNIT("Functions\FCN_lcase.cpp");
USEUNIT("Functions\FCN_legendre.cpp");
USEUNIT("Functions\FCN_ln.cpp");
USEUNIT("Functions\FCN_lnagamma.cpp");
USEUNIT("Functions\FCN_lnbeta.cpp");
USEUNIT("Functions\FCN_log10.cpp");
USEUNIT("Functions\FCN_log.cpp");
USEUNIT("Functions\FCN_logam.cpp");
USEUNIT("Functions\FCN_mod.cpp");
USEUNIT("Functions\FCN_nint.cpp");
USEUNIT("Functions\FCN_normal.cpp");
USEUNIT("Functions\FCN_null.cpp");
USEUNIT("Functions\FCN_pdiff.cpp");
USEUNIT("Functions\FCN_plmn.cpp");
USEUNIT("Functions\FCN_plmu.cpp");
USEUNIT("Functions\FCN_poica.cpp");
USEUNIT("Functions\FCN_poisson.cpp");
USEUNIT("Functions\FCN_prob.cpp");
USEUNIT("Functions\FCN_psi.cpp");
USEUNIT("Functions\FCN_racah.cpp");
USEUNIT("Functions\FCN_radmac.cpp");
USEUNIT("Functions\FCN_sec.cpp");
USEUNIT("Functions\FCN_secd.cpp");
USEUNIT("Functions\FCN_sign.cpp");
USEUNIT("Functions\FCN_simpleran.cpp");
USEUNIT("Functions\FCN_sin.cpp");
USEUNIT("Functions\FCN_sind.cpp");
USEUNIT("Functions\FCN_sinint.cpp");
USEUNIT("Functions\FCN_sqrt.cpp");
USEUNIT("Functions\FCN_string.cpp");
USEUNIT("Functions\FCN_struve0.cpp");
USEUNIT("Functions\FCN_struve1.cpp");
USEUNIT("Functions\FCN_student.cpp");
USEUNIT("Functions\FCN_studenti.cpp");
USEUNIT("Functions\FCN_tan.cpp");
USEUNIT("Functions\FCN_tand.cpp");
USEUNIT("Functions\FCN_tcase.cpp");
USEUNIT("Functions\FCN_time.cpp");
USEUNIT("Functions\FCN_tina.cpp");
USEUNIT("Functions\FCN_ucase.cpp");
USEUNIT("Functions\FCN_vartype.cpp");
USEUNIT("Functions\FCN_voigt.cpp");
USEUNIT("Functions\FCN_walsh.cpp");
USEUNIT("Functions\FCN_wign3j.cpp");
USEUNIT("Functions\FCN_wign6j.cpp");
USEUNIT("Functions\FCN_wign9j.cpp");
USEUNIT("Functions\FunctionDefinition.cpp");
USEUNIT("Functions\FunctionTable.cpp");
USEUNIT("Graphics\GRA_window.cpp");
USEUNIT("Graphics\GRA_arrow1.cpp");
USEUNIT("Graphics\GRA_arrow2.cpp");
USEUNIT("Graphics\GRA_arrow3.cpp");
USEUNIT("Graphics\GRA_asterisk.cpp");
USEUNIT("Graphics\GRA_axis.cpp");
USEUNIT("Graphics\GRA_bitmap.cpp");
USEUNIT("Graphics\GRA_boolCharacteristic.cpp");
USEUNIT("Graphics\GRA_borlandW32.cpp");
USEUNIT("Graphics\GRA_cartesianAxes.cpp");
USEUNIT("Graphics\GRA_cartesianCurve.cpp");
USEUNIT("Graphics\GRA_color.cpp");
USEUNIT("Graphics\GRA_colorCharacteristic.cpp");
USEUNIT("Graphics\GRA_colorControl.cpp");
USEUNIT("Graphics\GRA_colorMap.cpp");
USEUNIT("Graphics\GRA_cross.cpp");
USEUNIT("Graphics\GRA_crossPlus.cpp");
USEUNIT("Graphics\GRA_diamond.cpp");
USEUNIT("Graphics\GRA_diamondPlus.cpp");
USEUNIT("Graphics\GRA_distanceCharacteristic.cpp");
USEUNIT("Graphics\GRA_doubleCharacteristic.cpp");
USEUNIT("Graphics\GRA_drawableObject.cpp");
USEUNIT("Graphics\GRA_drawableText.cpp");
USEUNIT("Graphics\GRA_ellipse.cpp");
USEUNIT("Graphics\GRA_fontCharacteristic.cpp");
USEUNIT("Graphics\GRA_intCharacteristic.cpp");
USEUNIT("Graphics\GRA_jpeg.cpp");
USEUNIT("Graphics\GRA_legend.cpp");
USEUNIT("Graphics\GRA_multiLineFigure.cpp");
USEUNIT("Graphics\GRA_outputType.cpp");
USEUNIT("Graphics\GRA_plotSymbol.cpp");
USEUNIT("Graphics\GRA_plus.cpp");
USEUNIT("Graphics\GRA_point.cpp");
USEUNIT("Graphics\GRA_polygon.cpp");
USEUNIT("Graphics\GRA_polyline.cpp");
USEUNIT("Graphics\GRA_postscript.cpp");
USEUNIT("Graphics\GRA_rectangle.cpp");
USEUNIT("Graphics\GRA_setOfCharacteristics.cpp");
USEUNIT("Graphics\GRA_simpleText.cpp");
USEUNIT("Graphics\GRA_sizeCharacteristic.cpp");
USEUNIT("Graphics\GRA_star5pt.cpp");
USEUNIT("Graphics\GRA_stringCharacteristic.cpp");
USEUNIT("Graphics\GRA_thiessenTriangulation.cpp");
USEUNIT("Graphics\GRA_triangle.cpp");
USEUNIT("Operators\OperatorTable.cpp");
USEUNIT("Operators\OPR_and.cpp");
USEUNIT("Operators\OPR_divide.cpp");
USEUNIT("Operators\OPR_equals.cpp");
USEUNIT("Operators\OPR_exponentiation2.cpp");
USEUNIT("Operators\OPR_exponentiation.cpp");
USEUNIT("Operators\OPR_ge.cpp");
USEUNIT("Operators\OPR_gt.cpp");
USEUNIT("Operators\OPR_le.cpp");
USEUNIT("Operators\OPR_lt.cpp");
USEUNIT("Operators\OPR_minus.cpp");
USEUNIT("Operators\OPR_ne.cpp");
USEUNIT("Operators\OPR_not.cpp");
USEUNIT("Operators\OPR_or.cpp");
USEUNIT("Operators\OPR_plus.cpp");
USEUNIT("Parsing\Script.cpp");
USEUNIT("Parsing\ParseLine.cpp");
USEUNIT("Parsing\ParseToken.cpp");
USEUNIT("Utilities\UsefulFunctions.cpp");
USEUNIT("Utilities\ExString.cpp");
USEUNIT("Variables\Variable.cpp");
USEUNIT("Variables\NumericVariable.cpp");
USEUNIT("Variables\NVariableTable.cpp");
USEUNIT("Variables\TextVariable.cpp");
USEUNIT("Variables\TVariableTable.cpp");
USEUNIT("ExGlobals.cpp");
USELIB("C:\Program Files\HTML Help Workshop\lib\htmlhelp.lib");
USEUNIT("Graphics\GRA_borlandMetafile.cpp");
USEUNIT("Operators\OPR_multiply.cpp");
USEUNIT("Expression\Workspace.cpp");
USEUNIT("Expression\ExprCodes.cpp");
USEUNIT("Expression\Expression.cpp");
USEUNIT("Expression\ListVector.cpp");
USEUNIT("Functions\ScalarFunction.cpp");
USEUNIT("Functions\FCN_area.cpp");
USEUNIT("Functions\FCN_char.cpp");
USEUNIT("Functions\FCN_clen.cpp");
USEUNIT("Functions\FCN_convolute.cpp");
USEUNIT("Functions\FCN_deconvolute.cpp");
USEUNIT("Functions\FCN_deriv.cpp");
USEUNIT("Functions\FCN_det.cpp");
USEUNIT("Functions\FCN_eigen.cpp");
USEUNIT("Functions\FCN_eqs.cpp");
USEUNIT("Functions\FCN_evaluate.cpp");
USEUNIT("Functions\FCN_exist.cpp");
USEUNIT("Functions\FCN_fft.cpp");
USEUNIT("Functions\FCN_fold.cpp");
USEUNIT("Functions\FCN_gaussj.cpp");
USEUNIT("Functions\FCN_ichar.cpp");
USEUNIT("Functions\FCN_iclose.cpp");
USEUNIT("Functions\FCN_identity.cpp");
USEUNIT("Functions\FCN_iequal.cpp");
USEUNIT("Functions\FCN_ifft.cpp");
USEUNIT("Functions\FCN_index.cpp");
USEUNIT("Functions\FCN_integral.cpp");
USEUNIT("Functions\FCN_interpolate.cpp");
USEUNIT("Functions\FCN_inverse.cpp");
USEUNIT("Functions\FCN_join.cpp");
USEUNIT("Functions\FCN_len.cpp");
USEUNIT("Functions\FCN_max.cpp");
USEUNIT("Functions\FCN_min.cpp");
USEUNIT("Functions\FCN_nes.cpp");
USEUNIT("Functions\FCN_pfactors.cpp");
USEUNIT("Functions\FCN_prod.cpp");
USEUNIT("Functions\FCN_rchar.cpp");
USEUNIT("Functions\FCN_roll.cpp");
USEUNIT("Functions\FCN_rprod.cpp");
USEUNIT("Functions\FCN_rsum.cpp");
USEUNIT("Functions\FCN_savgol.cpp");
USEUNIT("Functions\FCN_smooth.cpp");
USEUNIT("Functions\FCN_splinterp.cpp");
USEUNIT("Functions\FCN_splsmooth.cpp");
USEUNIT("Functions\FCN_step.cpp");
USEUNIT("Functions\FCN_sub.cpp");
USEUNIT("Functions\FCN_sum.cpp");
USEUNIT("Functions\FCN_sup.cpp");
USEUNIT("Functions\FCN_varname.cpp");
USEUNIT("Functions\FCN_unfold.cpp");
USEUNIT("Functions\FCN_volume.cpp");
USEUNIT("Functions\FCN_where.cpp");
USEUNIT("Functions\FCN_wrap.cpp");
USEUNIT("Operators\ScalarOperator.cpp");
USEUNIT("Operators\OPR_concatenation.cpp");
USEUNIT("Operators\OPR_exclusiveOr.cpp");
USEUNIT("Operators\OPR_innerProduct.cpp");
USEUNIT("Operators\OPR_intersection.cpp");
USEUNIT("Operators\OPR_outerProduct.cpp");
USEUNIT("Operators\OPR_reflect.cpp");
USEUNIT("Operators\OPR_transpose.cpp");
USEUNIT("Operators\OPR_union.cpp");
USEUNIT("Variables\TextData.cpp");
USEUNIT("Variables\NumericData.cpp");
USELIB("C:\Programming\PNG\lpng128\libpngstat.lib");
USELIB("C:\Programming\GD\gd-2_0_3\gd2033.lib");
USELIB("C:\Programming\ZLIB\ZLIB_1.2.2\zlib.lib");
USELIB("C:\Programming\FreeType\freetype-2.1.9\FreeType.lib");
USEUNIT("Graphics\GRA_gd.cpp");
USEUNIT("Commands\CMD_density.cpp");
USEUNIT("Graphics\GRA_boxPlot.cpp");
USEUNIT("Graphics\GRA_densityPlot.cpp");
USEUNIT("Graphics\GRA_angleCharacteristic.cpp");
USEUNIT("Graphics\GRA_diffusionPlot.cpp");
USEUNIT("Graphics\GRA_gradientPlot.cpp");
USEUNIT("Graphics\GRA_ditheringPlot.cpp");
USEFORM("Forms\GraphNovice.cpp", GraphNoviceForm);
USEFORM("Forms\FitNovice.cpp", FitNoviceForm);
USELIB("C:\Programming\libxml2-2.6.20\win32\bin.bcb\libxml2.lib");
USEUNIT("Utilities\ExXML.cpp");
USEUNIT("Graphics\GRA_errorBar.cpp");
USEUNIT("Graphics\GRA_fontControl.cpp");
USEFORM("Forms\About.cpp", AboutBox);
USEUNIT("Commands\CMD_bestfit.cpp");
USEUNIT("Functions\FCN_bivinterp.cpp");
USEUNIT("Functions\FCN_bivsmooth.cpp");
USEFORM("Forms\StackCommandsForm.cpp", StackForm);
USEUNIT("Commands\CMD_stack.cpp");
USEUNIT("Commands\CMD_form.cpp");
USEFORM("Forms\HintForm.cpp", MainHintForm);
USEUNIT("Commands\CMD_restore.cpp");
USELIB("C:\Programming\MUD\mud.lib");
USEUNIT("Functions\FCN_canopen.cpp");
USELIB("C:\Programming\Minuit-1_7_9\lib\Minuit.lib");
USEUNIT("Commands\CMD_minuit.cpp");
USEUNIT("Commands\Extrema_fcn.cpp");
USEUNIT("Functions\FCN_mean.cpp");
USEUNIT("Functions\FCN_median.cpp");
USEUNIT("Functions\FCN_rms.cpp");
USEUNIT("Functions\FCN_stdev.cpp");
USEUNIT("Functions\FCN_adev.cpp");
USEUNIT("Functions\FCN_gmean.cpp");
USEUNIT("Functions\FCN_imin.cpp");
USEUNIT("Functions\FCN_imax.cpp");
USEUNIT("Functions\FCN_var.cpp");
USEUNIT("Functions\FCN_skew.cpp");
USEUNIT("Functions\FCN_kurt.cpp");
USEUNIT("Functions\FCN_tanh.cpp");
USEUNIT("Functions\FCN_acosh.cpp");
USEUNIT("Functions\FCN_acoth.cpp");
USEUNIT("Functions\FCN_acsch.cpp");
USEUNIT("Functions\FCN_asech.cpp");
USEUNIT("Functions\FCN_atanh.cpp");
USEUNIT("Functions\FCN_cosh.cpp");
USEUNIT("Functions\FCN_coth.cpp");
USEUNIT("Functions\FCN_csch.cpp");
USEUNIT("Functions\FCN_sech.cpp");
USEUNIT("Functions\FCN_sinh.cpp");
USEUNIT("Functions\FCN_asinh.cpp");
USEUNIT("Graphics\GRA_page.cpp");
USEUNIT("Commands\CMD_page.cpp");
USEFORM("Forms\SetAspectRatio.cpp", SetAspectRatioForm);
USEUNIT("Commands\CMD_dealias.cpp");
USEUNIT("Commands\CMD_alias.cpp");
USEUNIT("Commands\CMD_ellipse.cpp");
USEUNIT("Commands\CMD_polygon.cpp");
USEFORM("Forms\BasicColors.cpp", BasicColorsForm);
USEFORM("Forms\AxisPopup.cpp", AxisPopupForm);
USEFORM("Forms\CurvePopup.cpp", CurvePopupForm);
USEFORM("Forms\TextPopup.cpp", TextPopupForm);
USEFORM("Forms\LegendPopup.cpp", LegendPopupForm);
USEUNIT("Functions\FCN_heaviside.cpp");
USEUNIT("Graphics\GRA_polarCurve.cpp");
USEUNIT("Graphics\GRA_polarAxes.cpp");
USEFORM("Forms\ThreeDPlot.cpp", ThreeDPlotForm);
USEUNIT("Graphics\GRA_threeDPlot.cpp");
USEUNIT("Graphics\GRA_contourLine.cpp");
//---------------------------------------------------------------------------
WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
  try
  {
    Application->Initialize();
    //
    SplashScreenForm = new TSplashScreenForm(Application);
    SplashScreenForm->Show();
    SplashScreenForm->Update();
    //
    Application->Title = "extrema";
    Application->CreateForm(__classid(TMainForm), &MainForm);
                 Application->CreateForm(__classid(TMainGraphicsForm), &MainGraphicsForm);
                 SplashScreenForm->BringToFront();
    //
    Application->Run();
  }
  catch (Exception &e)
  {
    Application->ShowException( &e );
  }
  catch (...)
  {
  }
  return 0;
}
//---------------------------------------------------------------------
